<?php

namespace Slowlyo\OwlAdmin\Console;

use Illuminate\Console\Command;
use Slowlyo\OwlAdmin\Services\AdminApiService;
use Slowlyo\OwlAdmin\Services\AdminCodeGeneratorService;
use Slowlyo\OwlAdmin\Support\Apis\AdminBaseApi;
use Slowlyo\OwlAdmin\Support\CodeGenerator\ControllerGenerator;
use Throwable;

class GenRouteCommand extends Command
{
    protected $signature = 'admin:gen-route {--excluded=} {--dry-run : Preview generated route file without writing it}';

    protected $description = 'Generate admin route file.';

    /**
     * 生成后台路由文件，dry-run 模式只输出预览，避免自动化场景误覆盖 routes/admin.php。
     */
    public function handle(): int
    {
        try {
            [$routes, $stats] = $this->buildRoutes();
        } catch (Throwable $e) {
            // 路由生成依赖代码生成器和动态 API 表，数据库异常时输出摘要即可。
            $this->error($e->getMessage());

            return self::FAILURE;
        }

        $content = <<<EOF
<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router \$router) {
_content_
});
EOF;

        $content = str_replace('_content_', $routes, $content);

        $this->table(['Type', 'Count'], [
            ['generated', $stats['generated']],
            ['skipped', $stats['skipped']],
        ]);

        if ($this->option('dry-run')) {
            // dry-run 用于确认最终文件内容，不能写入磁盘。
            $this->line($content);

            return self::SUCCESS;
        }

        file_put_contents(base_path('routes/admin.php'), $content);

        $this->info(admin_trans('admin.console.route_generated'));

        return self::SUCCESS;
    }

    /**
     * 汇总代码生成器和动态 API 路由，并对无法生成的记录给出明确 warning。
     */
    protected function buildRoutes(): array
    {
        $excluded = $this->option('excluded');
        if ($excluded) {
            $excluded = explode(',', $excluded);
        }

        $routes = '';
        $stats = [
            'generated' => 0,
            'skipped'   => 0,
        ];

        // 代码生成器
        AdminCodeGeneratorService::make()->query()
            ->when($excluded, fn($query, $excluded) => $query->whereNotIn('id', $excluded))
            ->get()
            ->each(function ($item) use (&$routes, &$stats) {
                if (!$item->menu_info['enabled']) {
                    // 未启用的菜单不生成资源路由，和后台代码生成器开关保持一致。
                    $stats['skipped']++;

                    return;
                }

                $_route      = ltrim($item->menu_info['route'], '/');
                $_controller = '\\' . str_replace('/', '\\', $item->controller_name);

                try {
                    require_once ControllerGenerator::guessClassFileName($_controller);
                } catch (\Throwable $e) {
                    // 控制器文件不存在时继续处理其他记录，避免单条脏数据中断整次生成。
                    $this->warn(admin_trans('admin.console.route_controller_file_missing', ['title' => $item->title, 'controller' => $item->controller_name]));
                }

                if (!@class_exists($_controller)) {
                    // 类加载失败时不能生成路由，否则运行期会直接 fatal。
                    $this->warn(admin_trans('admin.console.route_controller_class_missing', ['title' => $item->title, 'controller' => $_controller]));
                    $stats['skipped']++;

                    return;
                }

                $routes .= <<<EOF
    // {$item->title}
    \$router->resource('{$_route}', {$_controller}::class);

EOF;
                $stats['generated']++;
            });

        // api
        AdminApiService::make()->query()->where('enabled', 1)->get()->each(function ($item) use (&$routes, &$stats) {
            $_route = ltrim($item->path, '/');

            if (!$this->validApiTemplate($item->template, $item->title)) {
                $stats['skipped']++;

                return;
            }

            $routes .= <<<EOF
    // {$item->title}
    \$router->{$item->method}('{$_route}', [\Slowlyo\OwlAdmin\Controllers\AdminApiController::class, 'index']);

EOF;
            $stats['generated']++;
        });

        return [$routes, $stats];
    }

    /**
     * 校验动态 API 模板，缺失或类型不对时跳过，避免生成无法执行的路由。
     */
    protected function validApiTemplate(string $template, string $title): bool
    {
        if (!class_exists($template)) {
            $this->warn(admin_trans('admin.console.route_api_template_missing', ['title' => $title, 'template' => $template]));

            return false;
        }

        if (!(new \ReflectionClass($template))->isSubclassOf(AdminBaseApi::class)) {
            $this->warn(admin_trans('admin.console.route_api_template_invalid', ['title' => $title, 'template' => $template]));

            return false;
        }

        return true;
    }
}
